FROM ubuntu:latest 

RUN apt update && \
    apt upgrade -y && \
    apt install nginx -y  && \
    systemctl enable nginx && \
    systemctl restart nginx
    
RUN rm -r /var/www/html/* && \
    echo "This is nginx container created from Dockerfile" > /usr/share/nginx/html/index.html

EXPOSE 80 

CMD ["nginx", "-g", "daemon off;"]      # start nginx in foreground


