pipeline {
  agent { label 'slave-1' }

  environment {
    AWS_REPO = '042666117784.dkr.ecr.us-east-1.amazonaws.com/push-from-pipeline' 
    IMAGE_TAG = "build-${env.BUILD_NUMBER}"
    DOCKER_CRED_ID = 'docker-hub-cred'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Image') {
      steps {
        script {
          sh 'docker build -t ${AWS_REPO}:${IMAGE_TAG} .'
        }
      }
    }

    stage('Test Image') {
      steps {
        script {
          sh '''
            CID=$(docker run -d -p 8080:80 ${AWS_REPO}:${IMAGE_TAG})
            docker rm -f $CID || true
          '''
        }
      }
    }

    stage('Login & Push to ECR') {
      steps {
        script {
            withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws-cred', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                sh """
                    aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 042666117784.dkr.ecr.us-east-1.amazonaws.com
                    docker push ${AWS_REPO}:${IMAGE_TAG}
                """
            }
                echo "Pushed ${AWS_REPO}:${IMAGE_TAG} to ECR."
        }
      }
    }

    stage('Cleanup') {
      steps {
        script {
          sh "docker rmi ${AWS_REPO}:${IMAGE_TAG} || true"
        }
      }
    }
  }

  post {
    success {
      echo "Image ${AWS_REPO}:${IMAGE_TAG} pushed successfully."
    }
    failure {
      echo "Pipeline failed. Check logs."
    }
  }
}

